### ISSUE TITLE
ModuleNotFoundError: No module named 'diff_gaussian_rasterization_depth'

### ISSUE THREAD

**Issue by misakamage** [ziweny11/PhotoRegCodes#3]
Hello! Thank you for the timely update. I prepared my data as required and tried running the code, but I encountered the error mentioned in the title. Specifically:

Traceback (most recent call last):
  File "/home/czy98/code_data/PhotoRegCodes/main.py", line 13, in <module>
    from gaussian_renderer import network_gui
  File "/home/czy98/code_data/PhotoRegCodes/gaussian_renderer/__init__.py", line 14, in <module>
    from diff_gaussian_rasterization_depth import GaussianRasterizationSettings, GaussianRasterizer
ModuleNotFoundError: No module named 'diff_gaussian_rasterization_depth'

Did you modify the diff_gaussian_rasterization module in the submodule but forget to upload the corresponding code?

**Comment by HowCCB** [comment]
change diff_gaussian_rasterization_depth to diff_gaussian_rasterization will fix this problem.
But I think that he maybe just forget updating the diff_gaussain_rasterization_depth code

**Comment by ziweny11** [comment]
Hi, sorry for the bug. I have updated and tested all the code, they should be able to work now. diff_gaussian_rasterization_depth is used as a submodule. You can replace it with diff_gaussian_rasterization for now or install it here: https://github.com/leo-frank/diff-gaussian-rasterization-depth
