### ISSUE TITLE
Spent hours fixing your bug. Obtained an unsatisfactory result.

### ISSUE THREAD

**Issue by zixinzhang02** [ziweny11/PhotoRegCodes#5]
Registration results on MIP-360 Dataset.
The results is not even wrong...
<img width="1908" alt="image" src="https://github.com/user-attachments/assets/9391cdac-3430-4271-afad-bdc0861283ad">
<img width="1250" alt="image" src="https://github.com/user-attachments/assets/c7e13be2-fe60-43a1-a77b-777b1dc5818f">

**Comment by ziweny11** [comment]
Hi, sorry for the bug. I have updated my code and tested on it. I believed this was caused by a bug in findpair.py. I forgot to normalize the images before storing them, so the transformation matrix returned by DUSt3R is always identity. it is fixed now.

**Comment by zixinzhang02** [comment]
Thanks for fixing the bug. I've retried the latest code, another error occurs during `loss.backward()` in function `finetuning`.
`RuntimeError: Function 'Atan2Backward0' returned nan values in its 0th output.`

**Comment by ziweny11** [comment]
I have never met that bug before, can you provide a full error output? Also what dataset are you running it on?

**Comment by zixinzhang02** [comment]
```
...
...
...
len of usable RT_list: 58
Epochs:   0%|                                                                                                                                                | 0/10 [00:00<?, ?it/s]/home/zixinzhang/data0/anaconda3/envs/photoreg/lib/python3.10/site-packages/torch/autograd/__init__.py:200: UserWarning: Error detected in Atan2Backward0. No forward pass information available. Enable detect anomaly during forward pass for more information. (Triggered internally at /opt/conda/conda-bld/pytorch_1678411187366/work/torch/csrc/autograd/python_anomaly_mode.cpp:92.)
  Variable._execution_engine.run_backward(  # Calls into the C++ engine to run the backward pass
Epochs:   0%|                                                                                                                                                | 0/10 [00:00<?, ?it/s]
Traceback (most recent call last):
  File "/home/ps/data/zixinzhang/data0/photoreg/main.py", line 61, in <module>
    best_loss, offset, rot, Sscale, Tscale = finetuning(lp.extract(args), op.extract(args), pp.extract(args), args.test_iterations, args.save_iterations, args.checkpoint_iterations, args.start_checkpoint, args.start_checkpoint2, args.debug_from,
  File "/home/ps/data/zixinzhang/data0/photoreg/finetuning.py", line 278, in finetuning
    loss.backward()
  File "/home/zixinzhang/data0/anaconda3/envs/photoreg/lib/python3.10/site-packages/torch/_tensor.py", line 487, in backward
    torch.autograd.backward(
  File "/home/zixinzhang/data0/anaconda3/envs/photoreg/lib/python3.10/site-packages/torch/autograd/__init__.py", line 200, in backward
    Variable._execution_engine.run_backward(  # Calls into the C++ engine to run the backward pass
RuntimeError: Function 'Atan2Backward0' returned nan values in its 0th output.
```
I've run 2 dataset, a 3dgs classic dataset `tandt/train` and a mip-360 dataset `kitchen`, same error occurs.
They are all trained with original 3dgs code, and the checkpoint were then input into the photoreg code.

**Comment by ziweny11** [comment]
Could it be due to environment problem? I recommend setting up a new environment. For instance, I used Python 3.8 in my setup, and I’ll provide the specific package versions tmr if needed.

**Comment by zixinzhang02** [comment]
Thanks, I'll try to set up a new environment and try it again.

**Comment by Li-Yuetao** [comment]
> Thanks for fixing the bug. I've retried the latest code, another error occurs during `loss.backward()` in function `finetuning`. `RuntimeError: Function 'Atan2Backward0' returned nan values in its 0th output.`

Hello, I also got this error when running the default ‘main.py’. My python version is 3.8  .Have you solved it?

**Comment by ziweny11** [comment]
Hi, Looks like not an environment problem. The following update to the extract_RT function in coarseReg.py should solve it:
```
def extract_RT(m):
    if m.shape[0] < 2 or m.shape[1] < 4 or m.shape[2] < 4:
        raise ValueError("invalid matrix obtained from dust3r")

    identity = np.eye(4)

    if not np.allclose(m[0], identity):
        inv_m0 = np.linalg.inv(m[0])
        m[1] = np.dot(inv_m0, m[1])
    R = m[1][:3, :3]
    T = m[1][:3, 3]

    return R, T
```
I will make a commit on this.
The reason is due to an inconsistency in how DUSt3R returns transformation matrices, sometimes reversing the expected order, so the code need to standardize this and always align the second coordinate frame to the first.

**Comment by zixinzhang02** [comment]
Thanks, the code works in some dataset after changing the `extract_RT`. However, in some dataset, the `cam_RT_list1` in https://github.com/ziweny11/PhotoRegCodes/blob/1a811186f22cf9ac93ceb0050ae9255f3698e921/finetuning.py#L153-L154 returns None. How do I need to modify the threshold in function `filtercam` https://github.com/ziweny11/PhotoRegCodes/blob/1a811186f22cf9ac93ceb0050ae9255f3698e921/finetuning.py#L52 to get a valid `cam_RT_list1`?

**Comment by ziweny11** [comment]
`threshold` measures blurriness, range `[0, 1]`; higher values indicate greater blurriness. `sim_threshold` measures image similarity, range `[0, 1]`, where higher values mean more similar. Therefore, I believe the most lenient condition would be `threshold = 1.0 and sim_threshold = 0.0`. Hope this clarifies things!

**Comment by zixinzhang02** [comment]
Thanks!
